### ISSUE TITLE
Kinda weird thing...

### ISSUE THREAD

**Issue by petercampanelli** [soops/christopher#1]
Turing actually didn't name the Enigma cracking machine Christopher (https://en.wikipedia.org/wiki/The_Imitation_Game#Historical_events). I only know this since I'm researching him for a paper.

**Comment by ethel-dev** [comment]
Oh thanks, not changing the name but I'll change the story. Feel like an idiot now lol

**Comment by petercampanelli** [comment]
Dude its still a good name. Just fix the story. Good plan.
